# k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-predictor
  template:
    metadata:
      labels:
        app: ml-predictor
    spec:
      containers:
      - name: ml-predictor
        image: ml-predictor:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: ml-predictor-service
spec:
  type: NodePort
  selector:
    app: ml-predictor
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
